CLASS_NAMES = {
    "ftagTruthOriginLabel": [
        "Pileup",
        "Fake",
        "Primary",
        "FromB",
        "FromBC",
        "FromC",
        "FromTau",
        "OtherSecondary",
    ],
    "ftagTruthTypeLabel": [
        "NoTruth",
        "Other",
        "Pion",
        "Kaon",
        "Electron",
        "Muon",
    ],
    # "flavour_label":[
	# 	"tttt",
    #     "ttt",
    #     "ttV",
    #     "otherbkg",
    # ],
    "flavour_label":[
		"ttZp_mZp1000",
        "tttt_ttt",
        "ttV",
        "otherbkg",
    ],
    "truth_label":[
        "NonMatch",
        "Top",
        "Higgs",
    ],
    "isLight":[
        "NonMatch",
        "False",
        "True",
    ],
    "isCharm":[
        "NonMatch",
        "False",
        "True",
    ],
    "isBottom":[
        # "NonMatch",
        "False",
        "True",
    ],
    "isTau":[
        "NonMatch",
        "False",
        "True",
    ],
    "isFromTop":[
        "NonMatch",
        "False",
        "True",
    ],
    "isFromH":[
        "NonMatch",
        "False",
        "True",
    ],
    # "isFromZ":[
    #     "NonMatch",
    #     "False",
    #     "True",
    # ],
    "vertex_Tops":[
        "NonMatch",
        "First",
        "Second",
        "Third",
        "Fourth",
    ],
    "vertex_Higgs":[
        "NonMatch",
        "First",
        "Second",
    ],
    # "vertex_Zs":[
    #     "NonMatch",
    #     "First",
    #     "Second",
    # ],
    # "originIndexZp":[
    #     "NonMatch",
    #     "FirstZp",
    #     "SecondZp",
    #     "ThirdZp",
    #     "FourthZp",
    # ],
    # "originIndexTop":[
    #     "NonMatch",
    #     "FirstTop",
    #     "SecondTop",
    #     "ThirdTop",
    #     "FourthTop",
    # ],
    # "originIndexW":[
    #     "NonMatch",
    #     "FirstW",
    #     "SecondW",
    #     "ThirdW",
    #     "FourthW",
    # ],
    "truthflav":[
        "NonJet",
        "light",
        "charm",
        "bottom",
        "tau",
    ],
    "truth_vertex":[
        "NonMatch",
        "First",
        "Second",
        "Third",
        "Fourth",
    ],
}
